---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: win2012r2

suites:
  - name: default
    run_list:
      - recipe[iis-lb::default]
    attributes:
