name 'iis-lb'
maintainer 'Bakh Inamov'
maintainer_email 'b@chef.io'
license 'all_rights'
description 'Installs/Configures iis-lb'
long_description 'Installs/Configures iis-lb'
version '0.1.6'

depends 'windows'
depends 'webpi'
depends 'iis'
